version: '3.1'

services:

  mysql:
    image: mysql:8.0.22
    restart: always
    ports:
      - 3306:3306
    command: "mysqld --secure-file-priv /home/project"
    volumes:
      - /home/project:/home/project
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: mysqladmin ping -uroot -p${TESTSUITE_PASSWORD:-my-secret-pw}
      start_period: 5s
      interval: 5s
      timeout: 60s
      retries: 10

  phpmyadmin:
    image: us.icr.io/sn-labsassets/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      # PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: curl -Ss http://localhost/robots.txt
      start_period: 5s
      interval: 3s
      timeout: 60s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
